version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo "Inicio de fase de pre-build"
  build:
    commands:
    - echo "Inicio de fase de build"
    - mvn clean prepare-package war:exploded
  post_build:
    commands:
    - echo "Inicio de fase de post-build"
    - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*