version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - echo "Inicio de fase de pre-build"
  build:
    commands:
    - echo "Inicio de fase de build"
    - mvn package
  post_build:
    commands:
    - echo "Inicio de fase de post-build"
artifacts:
  files:
    - target/redis-test-0.0.1-SNAPSHOT.jar
  discard-paths: yes